#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XamarinCuboidCircleButtonBinding.Resource", IsApplication=true)]

namespace XamarinCuboidCircleButtonBinding
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F010000
			public const int cub_border_color = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int cub_border_radius = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int cub_color = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int cub_fontstyle = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int cub_hover_color = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int cub_icon = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int cub_riple_effect = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int fontName = 2130771975;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F020000
			public const int colorAccent = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int colorAccent2 = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int colorPrimary = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int colorPrimaryDark = 2130837507;
			
			// aapt resource value: 0x7F02001D
			public const int colorwhite = 2130837533;
			
			// aapt resource value: 0x7F020004
			public const int color_00796B = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int color_009688 = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int color_00BFFF1 = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int color_0288D1 = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int color_03A9F4 = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int color_239bbe = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int color_37718E = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int color_388E3C = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int color_4062BB = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int color_448AFF = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int color_4CAF50 = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int color_59C3C3 = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int color_8BC34A = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int color_8EE3EF = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int color_AEF3E7 = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int color_CDDC39 = 2130837523;
			
			// aapt resource value: 0x7F020019
			public const int color_d7bb65 = 2130837529;
			
			// aapt resource value: 0x7F020014
			public const int color_EBEBEB = 2130837524;
			
			// aapt resource value: 0x7F020015
			public const int color_F45B69 = 2130837525;
			
			// aapt resource value: 0x7F020016
			public const int color_F57C00 = 2130837526;
			
			// aapt resource value: 0x7F020017
			public const int color_FF5722 = 2130837527;
			
			// aapt resource value: 0x7F020018
			public const int color_FF9800 = 2130837528;
			
			// aapt resource value: 0x7F02001A
			public const int color_pd = 2130837530;
			
			// aapt resource value: 0x7F02001B
			public const int color_pl = 2130837531;
			
			// aapt resource value: 0x7F02001C
			public const int color_pt = 2130837532;
			
			// aapt resource value: 0x7F02001E
			public const int cream = 2130837534;
			
			// aapt resource value: 0x7F02001F
			public const int ic_launcher_background = 2130837535;
			
			// aapt resource value: 0x7F020020
			public const int red = 2130837536;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F030000
			public const int fab_margin = 2130903040;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F040004
			public const int icon_android = 2130968580;
			
			// aapt resource value: 0x7F040000
			public const int ic_camera = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int ic_launcher = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int ic_launcher_background = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int ic_settings = 2130968579;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F050000
			public const int action_settings = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int idImg = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int test_issues = 2131034114;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F060000
			public const int activity_main = 2131099648;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7F070000
			public const int menu_main = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F080000
			public const int ic_launcher = 2131230720;
			
			// aapt resource value: 0x7F080001
			public const int ic_launcher_foreground = 2131230721;
			
			// aapt resource value: 0x7F080002
			public const int ic_launcher_round = 2131230722;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F090000
			public const int action_settings = 2131296256;
			
			// aapt resource value: 0x7F090001
			public const int app_name = 2131296257;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F0A0000
			public const int AppTheme = 2131361792;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x7F010007 }
			public static int[] CustomTextView = new int[] {
					2130771975};
			
			// aapt resource value: 0
			public const int CustomTextView_fontName = 0;
			
			// aapt resource value: { 0x7F010000,0x7F010001,0x7F010002,0x7F010003,0x7F010004,0x7F010005,0x7F010006 }
			public static int[] MyCircleView = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974};
			
			// aapt resource value: 0
			public const int MyCircleView_cub_border_color = 0;
			
			// aapt resource value: 1
			public const int MyCircleView_cub_border_radius = 1;
			
			// aapt resource value: 2
			public const int MyCircleView_cub_color = 2;
			
			// aapt resource value: 3
			public const int MyCircleView_cub_fontstyle = 3;
			
			// aapt resource value: 4
			public const int MyCircleView_cub_hover_color = 4;
			
			// aapt resource value: 5
			public const int MyCircleView_cub_icon = 5;
			
			// aapt resource value: 6
			public const int MyCircleView_cub_riple_effect = 6;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
